module.exports = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  Fla: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  Mich: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  Miss: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  "New Mex": "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvia",
  Penn: "Pennsylvia",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  Tenn: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  Wash: "Washington",
  WV: "West Virgina",
  WI: "Wisconsin",
  WY: "Wyoming",
  St: "State",
  Intl: "International",
  W: ["West", "Western"],
  N: ["Northern", "North", "New"],
  S: ["Southern", "South"],
  Col: "College",
  U: "University",
  E: ["Eastern", "East"],
  Car: "Carolina",
  Grn: "Green",
  Ant: "Antonio",
  Mississippi: "Miss",
  "TX Christian": "TCU",
  BYU: "Brigham Young",
  "TX El Paso": "UTEP",
  "LA Lafayette": "Louisiana-Lafayette",
  "Central FL": "UCF",
  "Middle Tenn": "Middle Tennessee State",
  "U Mass": "Massachusetts",
  App: "Appalachian",
  Mex: "Mexico"
};
